version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  api-service:
    image: com.peopleflow/api:1.0-SNAPSHOT
    container_name: peopleflow-api
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    environment:
      - "SPRING_PROFILES_ACTIVE=doc"

  employee-service:
    image: com.peopleflow/employee-service:1.0-SNAPSHOT
    container_name: peopleflow-employee-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    environment:
      - "SPRING_PROFILES_ACTIVE=doc"

  nginx:
    image: nginx:latest
    volumes:
      - ./resources/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - api-service
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local