server:
  port: 8081
kafka:
  employee:
    topic: employee
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/peopleflow
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: ${kafka_bootstrap_servers:localhost:9092}
    producer:
      client-id: api
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false