server:
  port: 8082
kafka:
  employee:
    topic: employee

spring:
  kafka:
    bootstrap-servers: ${kafka_bootstrap_servers:localhost:9092}
    consumer:
      auto-offset-reset: latest
      group-id: employee
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer2
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer2
      max-poll-records: 1
      client-id: employee-service
      properties:
        spring.json.trusted.packages: com.peopleflow.lib
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer